### ISSUE TITLE
Inject ONM_URL variable on cluster creation

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/nebulous#4]
New version of ONM cluster initialization scripts require env variable ONM_URL.

Optimiser controller has to inject it. The value has to be given to the optimiser controller via environment variables.

- [x] Update optimiser controller (@rudi )
- [x] Update the deployment of the optimiser controller to provide the value for it (158.37.63.36:8082 for now) (@jmarchel7bulls )
- [x] Update documentation [of the necessary env variables ](https://openproject.nebulouscloud.eu/projects/nebulous-collaboration-hub/wiki/env-variables-for-nebulous-application-deployment-scripts)

**Comment by rudi** [comment]
https://github.com/eu-nebulous/optimiser-controller/blob/902729b4cdd6fb8004b95a2cada09cc9f390992b/optimiser-controller/src/main/java/eu/nebulouscloud/optimiser/controller/NebulousAppDeployer.java#L426 says that this is already done.  @robert-sanfeliu do you see the warning in the log ("Overlay Network Manager address (ONM_URL) is not set..."), otherwise ONM_URL should be set already.

**Comment by rudi** [comment]
That being said, I just fixed a trivial typo in `values.yaml`, maybe that was the reason that `ONM_URL` wasn't picked up? (see https://github.com/eu-nebulous/optimiser-controller/pull/10)

**Comment by jmarchel7bulls** [comment]
can we close??
